# Generated by Django 3.2 on 2023-06-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('esomedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVisual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esomedia.image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('published', models.BooleanField(default=False)),
                ('publication_datetime', models.DateTimeField()),
                ('embargo_datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('main_text', models.TextField()),
                ('more_information', models.TextField()),
                ('links', models.TextField()),
                ('contacts', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.category')),
                ('images', models.ManyToManyField(through='release.ImageVisual', to='esomedia.Image')),
                ('tags', models.ManyToManyField(to='utils.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoVisual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('press_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.pressrelease')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esomedia.video')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='pressrelease',
            name='videos',
            field=models.ManyToManyField(through='release.VideoVisual', to='esomedia.Video'),
        ),
        migrations.AddField(
            model_name='imagevisual',
            name='press_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.pressrelease'),
        ),
    ]
