# Generated by Django 3.2 on 2023-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmselements', '0002_header_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
