# Generated by Django 3.2 on 2023-06-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cmselements', '0003_header_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmselements_container', serialize=False, to='cms.cmsplugin')),
                ('background', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='li', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SectionHeading',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmselements_sectionheading', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('include_social_media', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
